[package]
name = "air-traffic-simulator-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
dubins_paths = { version = "2.4.0", features = ["glam"] }
duplicate = "1.0.0"
glam = { version = "0.29.0", features = ["serde"] }
eyre = "0.6.12"
itertools = "0.13.0"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.209", features = ["rc", "derive"] }
smol_str = { version = "0.2.2", features = ["serde"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
assertables = "7.0.1"
proptest = "1.5.0"
tracing-test = "0.2.5"

[lints]
workspace = true