[package]
name = "air-traffic-simulator-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.28.0", features = ["serde"] }
serde = { version = "1.0.204", features = ["rc", "derive"] }
smol_str = { version = "0.2.2", features = ["serde"] }
eyre = "0.6.12"
itertools = "0.13.0"
derive_more = { version = "1.0.0-beta.7", features = ["full"] }
duplicate = "1.0.0"
dubins_paths = { version = "2.3.1", features = ["glam"] }

[dev-dependencies]
proptest = "1.5.0"
