[package]
name = "air-traffic-simulator-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.24.1", features = ["serde"] }
serde = { version = "1.0.188", features = ["rc"] }
smol_str = { version = "0.2.0", features = ["serde"] }
eyre = "0.6.8"