[package]
name = "air-traffic-simulator-server"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine", package = "air-traffic-simulator-engine" }

axum = "0.7.5"
eyre = "0.6.12"
fs_extra = "1.3.0"
itertools = "0.13.0"
serde = "1.0.209"
socketioxide = { version = "0.14.1", features = ["state", "tracing"] }
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
tokio = { version = "1.39.3", features = ["full"] }
tempfile = "3.12.0"
tracing = "0.1.40"

[build-dependencies]
eyre = "0.6.12"

[features]
default = ["client"]
client = []

[lints]
workspace = true